apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-auth-hpa
  namespace: orderly
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-auth-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
