apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-auth-configmap
  namespace: orderly
data:
  PORT: "3000"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_DATABASE: "${DB_NAME}"
  DB_SERVER: "${DB_SERVER}"
  JWT_KEY: "${TOKEN_SECRET}"
  BCRYPT_COST: "12"
  AUTH_URL: http://kong-service:8001
  CONSUMER: "orderly"
