apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth-deployment
  namespace: orderly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-auth
  template:
    metadata:
      labels:
        app: ms-auth
    spec:
      containers:
      - name: ms-auth-container
        image: dealmachine/auth-api:2
        workingDir: /usr/auth/api
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: ms-auth-configmap
